import type { Metadata } from "next";
import Script from 'next/script'
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "./components/footer";
import HeaderWrapper from "./components/header-wrapper";
import CartSidebar from "./components/CartSidebar"; // ✅ ADD THIS
import { CartProvider } from "./context/CartContext";
import { LogProvider } from "./context/LogContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SHI UC HUB",
  description: "Generated by create next app",
};

import { Toaster } from "react-hot-toast"; // ✅ ADD THIS

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} font-sans antialiased flex flex-col min-h-screen`}
      >
        <CartProvider>
          <LogProvider>
            <HeaderWrapper />

            {/* ✅ CART SIDEBAR */}
            <CartSidebar />

            <main className="flex-grow pt-18 md:pt-20 lg:pt-15 overflow-y-auto">
              {children}
            </main>

            <Footer />
            <Toaster
              position="top-right"
              toastOptions={{
                style: {
                  fontSize: '12px',
                },
              }}
            /> {/* ✅ ENABLE TOASTS */}
          </LogProvider>
        </CartProvider>
        <Script
          id="tawk-to"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5e82206635bcbb0c9aabf012/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
            `,
          }}
        />

      </body>
    </html>
  );
}
